### ISSUE TITLE
Native components fails to install

### ISSUE THREAD

**Issue by brooksgarrett** [saltstack-formulas/tomcat-formula#21]
---

```
      ID: libtcnative-1
Function: pkg.installed
  Result: False
 Comment: The following package(s) were not found, and no possible matches were found in the package db: libtcnative-1
 Started:
 Duration:
 Changes:
```

---

Looks like the package name is incorrect for RedHat, I'll issue a PR for the updated map.
