### ISSUE TITLE
Debian settings in osmap.yaml conflict

### ISSUE THREAD

**Issue by hemebond** [saltstack-formulas/tomcat-formula#39]
Everything is hard-coded for tomcat8, ignoring the version and requiring the user override every property.

```
          ID: tomcat
    Function: pkg.installed
        Name: tomcat8
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - E: Version '7' for 'tomcat8' was not found
     Started: 15:26:08.279425
    Duration: 67624.108 ms
     Changes:   
```
The version property now refers to the package version rather than the major version e.g., 7 or 8.
