### ISSUE TITLE
SUSE: wrong ver inherited by tomcat.config state

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#78]
SUSE uses tomcat 8 but inherits wrong version value from defaults.yaml leading to inconsistent configuration being applied (see below).  Adding`suse.ver` to osmap.yaml fixes the issue.

Extract from [suse_tomcat_resultt.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1357616/suse_tomcat_resultt.log.txt)
```
limits_conf:

  file.managed:
    - name: /etc/security/limits.d/tomcat7.conf
    - contents:
```
Wanted configuration:
```
limits_conf:

  file.managed:
    - name: /etc/security/limits.d/tomcat8.conf
    - contents:
```
