### ISSUE TITLE
Mysterious tomcat.version variable in init.sls

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#81]
The `init.sls` refers to a `tomcat.version` variable not defined or referenced elsewhere.
```
tomcat:
  pkg.installed:
    - name: {{ tomcat.pkg }}
    {% if tomcat.version is defined %}
    - version: {{ tomcat.version }}
    {% endif %}
```

Maybe the following was intended?

```
tomcat:
  pkg.installed:
    - name: {{ tomcat.pkg }}
    - version: '{{ tomcat.ver }}*'
```

**Comment by noelmcloughlin** [comment]
Using `version: '{{ tomcat.ver }}*'` works with salt.pkg.installed on MacOS.

```
         ID: tomcat
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: tomcat=8*
     Started: 11:21:07.351304
    Duration: 6539.052 ms
     Changes:
              ----------
              tomcat:
                  ----------
                  new:
                      8.5.27
                  old:
```
